argocd:

  kube-prometheus-stack:
    enabled: true

  loki:
    enabled: false

  promtail:
    enabled: false

  ingress-nginx:
    enabled: true
  
  keycloak:
    enabled: true

  cert-manager: 
    enabled: true
  
  gitlab:
    enabled: true