applications:
  - name: keycloak
    namespace: keycloak
    enabled: true
  - name: gitlab
    namespace: gitlab
    enabled: false
  - name: promtail
    namespace: monitoring
    enabled: true
  - name: kube-prometheus-stack
    namespace: monitoring
    enabled: true
  - name: loki
    namespace: loki
    enabled: true
  - name: cert-manager
    namespace: cert-manager
    enabled: true
  - name: ingress-nginx
    namespace: ingress-nginx
    enabled: true