{{- if (index (index (index .Values "argocd") "gitlab") "enabled") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://charts.gitlab.io/'
    chart: gitlab
    targetRevision: 9.2.1
    helm:
      valueFiles:
      - $values/values/gitlab.yaml
  - repoURL: 'https://github.com/samuelamaralls/app-of-apps-infra.git'
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  destination:
    namespace: gitlab
    server: https://kubernetes.default.svc
{{- end }}
