{{- if (index (index (index .Values "argocd") "keycloak") "enabled") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  sources:
    - chart: keycloak
      #repoURL: oci://registry-1.docker.io/bitnamicharts
      repoURL: https://repo.broadcom.com/bitnami-files
      targetRevision: 24.8.0
      helm:
        valueFiles:
          - $values/values.yaml
    - repoURL: 'https://github.com/samuelamaralls/app-of-apps-infra.git'
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}