{{- if (index (index (index .Values "argocd") "kube-prometheus-stack") "enabled") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 75.15.0
    helm:
      valueFiles:
      - $values/values.yaml
      parameters:
      - name: crds.create
        value: "false"
  - repoURL: 'https://github.com/samuelamaralls/app-of-apps-infra.git'
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - SkipCRDs=true
    - CreateNamespace=true
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
{{- end }}